#!/usr/bin/bash
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PATH="$DIR:$PATH"
for file in $* ; do
	echo "$file"
	cat "$file" | sed -E -e 's/\s+/ /g' -e 's/;.*//' -e 's/^\s//' -e 's/\s$//' -e '/^$/d' |
		pcsmvn-objdump.py
done
